pipeline {
    agent any
    environment{
        SONARQUBE_HOSTNAME = 'localhost'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    echo 'Building...'
                    sh 'npm install'  
                    //sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Lógica para ejecutar pruebas
                    echo 'Running tests...'
                    sh 'npm test'  
                }
            }
        }

        stage('Lint') {
            steps {
                script {
                    echo 'Linting...'
                    sh 'npm run lint'  
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                    withCredentials([usernamePassword(credentialsId: 'sonar', usernameVariable: 'USER', passwordVariable: 'PASS' )]) {
                    sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://${SONARQUBE_HOSTNAME}:9000 -Dsonar.login=${USER}:${PASS} -Dsonar.projectName=fsweb -Dsonar.projectVersion=${env.BUILD_NUMBER} -Dsonar.projectKey=GS -Dsonar.sources=src/main/ -Dsonar.tests=src/test/ -Dsonar.java.binaries=build/**/* -Dsonar.language=java"
                    }
                }
            }
        }
    }
}