pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Lógica para construir tu proyecto
                    echo 'Building...'
                    sh 'npm install'  // Ejemplo para un proyecto de Node.js, ajusta según tu tecnología
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Lógica para ejecutar pruebas
                    echo 'Running tests...'
                    sh 'npm test'  // Ejemplo para un proyecto de Node.js, ajusta según tu tecnología
                }
            }
        }

        stage('Lint') {
            steps {
                script {
                    // Lógica para ejecutar linters
                    echo 'Linting...'
                    sh 'npm run lint'  // Ejemplo para un proyecto de Node.js, ajusta según tu tecnología
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    // Lógica para ejecutar el análisis de SonarQube
                    echo 'Running SonarQube analysis...'
                    // Asegúrate de configurar las propiedades adecuadas para tu proyecto
                    // Aquí, se asume que SonarQube Scanner ya está instalado y configurado en tu entorno
                    sh 'sonar-scanner'
                }
            }
        }

        // Puedes agregar más etapas según sea necesario

    }
}
