pipeline {
    agent any

    environment {
        NEXUS_CREDENTIAL_ID = 'Nexus'
        NEXUS_REPOSITORY = 'FStackRepo'
        NEXUS_REGISTRY = 'http://localhost:8081'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t webapp:latest .'
                    // Añadir resto de comandos
                }
            }
        }

        stage('Push to Nexus') {
            steps {
                script {
                    // Tag de la imagen Docker
                    def dockerImageTag = "webapp:latest"
                    // Construir la URL de destino en Nexus
                    def nexusDockerImage = "${NEXUS_REGISTRY}/repository/${NEXUS_REPOSITORY}/webapp/${dockerImageTag}/"
                    
                    // Autenticación en Nexus
                    withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIAL_ID, usernameVariable: 'NEXUS_USERNAME', passwordVariable: 'NEXUS_PASSWORD')]) {
                        // Hacer login en Nexus
                        sh "echo \$NEXUS_PASSWORD | docker login -u \$NEXUS_USERNAME --password-stdin \$NEXUS_REGISTRY"
                        // Hacer tag y push de la imagen a Nexus
                        sh "docker tag ${dockerImageTag} ${nexusDockerImage}"
                        sh "docker push ${nexusDockerImage}"

                        }
                    }
                }
            }
        }
    }

