pipeline {
    agent any

    environment {
        NEXUS_CREDENTIAL_ID = 'Nexus'
        NEXUS_REPOSITORY = 'FStackRepo'
        VERSION = '1.0.0'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t webapp:latest .'
                    // Añadir resto de comandos
                }
            }
        }

        stage('Push to Nexus') {
            steps {
                script {
                    // Tag de la imagen Docker
                    dockerImageTag = "webapp:latest"
                    // Construir la URL de destino en Nexus
                    nexusUrl = "http://localhost:8081/repository/${nexusRepository}/webapp/${dockerImageTag}/"
                    
                    // Autenticación en Nexus
                    withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIAL_ID, usernameVariable: 'NEXUS_USERNAME', passwordVariable: 'NEXUS_PASSWORD')]) {
                        // Hacer push de la imagen a Nexus
                        sh "docker tag ${dockerImageTag} ${nexusUrl}"
                        sh "docker login -u ${NEXUS_USERNAME} -p ${NEXUS_PASSWORD} ${nexusUrl}"
                        sh "docker push ${nexusUrl}"
                        }
                    }
                }
            }
        }
    }

