pipeline {
    agent any
    environment {
        NEXUS_CREDS = credentials('Nexus')
        NEXUS_DOCKER_REPO = 'localhost:9002'
    }

    stages {
       
       stage('Docker Build') {
        
            steps { 
                    echo 'Building docker Image'
                    sh 'docker build -t $NEXUS_DOCKER_REPO/fsweb:$BUILD_NUMBER .'
                }
        }

       stage('Docker Login') {
            steps {
                echo 'Nexus Docker Repository Login'
                script{
                    withCredentials([usernamePassword(credentialsId: 'Nexus', usernameVariable: 'USER', passwordVariable: 'PASS' )]){
                       sh ' echo $PASS | docker login -u $USER --password-stdin $NEXUS_DOCKER_REPO'
                    }
                   
                }
            }
        }

        stage('Docker Push') {
            steps {
                echo 'Pushing Imgaet to docker hub'
                sh 'docker push  $NEXUS_DOCKER_REPO/fsweb:$BUILD_NUMBER'
            }
        }
    }
}

