name: Build and push Docker image to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t fsweb .

      - name: Tag Docker Image
        run: |
          docker tag fsweb docker.pkg.github.com/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/fsweb:latest

      - name: Authenticate with GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: |
          docker push docker.pkg.github.com/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')/fsweb:latest
