name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Build Project
        run: |
          ./gradlew build
        working-directory: path/to/your/project

      - name: SonarCloud Scan
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_key \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONARCLOUD_TOKEN
        working-directory: path/to/your/project
        env:
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
